[versions]
minSdk = "24"
compileSdk = "35"

agp = "8.7.2"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.22"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
navigation = "2.8.2"
datastore = "1.1.1"
room = "2.6.1"

hilt = "2.52"
hilt-androidx = "1.2.0"

composeBom = "2024.09.02"
compose-coil = "2.6.0"
compose-activity = "1.9.2"

compose-ui = "1.7.5"
material3 = "1.3.1"

appcompat = "1.7.0"
material = "1.12.0"
core-splashscreen = "1.0.1"

composeNavigation = "2.8.3"
jetbrainsKotlinJvm = "2.0.20"
serialization = "1.7.3"


[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
kotlinx-immutables = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version = "0.3.7" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "compose-coil" }


# Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
#noinspection SimilarGradleDependency
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-ui" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-ui" }

animation = { module = "androidx.compose.animation:animation", version.ref = "compose-ui" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics", version.ref = "compose-ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-ui" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose-ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose-ui" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose-ui" }

compose-material = { module = "androidx.compose.material:material", name = "1.6.8" }

material3-core = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose-ui" }


# Hilt
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-androidx" }
hilt-androidx-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-androidx" }

# Work manager
work-manager = { module = "androidx.work:work-runtime-ktx", version = "2.10.0" }
work-manager-dagger = { module = "androidx.hilt:hilt-work", version = "1.2.0" }

# Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

#networking
retrofit = { module = "com.squareup.retrofit2:retrofit", version = "2.9.0" }
retrofit-gson-convertor = { module = "com.squareup.retrofit2:converter-gson", version = "2.9.0" }

# Room
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
#noinspection SimilarGradleDependency
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

[bundles]
compose-android = [
    "activity-compose", "foundation", "animation", "animation-graphics", "compose-ui",
    "material3-core", "material-icons", "ui-tooling-preview"
]